# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HubzuApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for HubzuApp
  pod 'Firebase/Core', '~> 5.15.0'
  pod 'Firebase/Messaging'
  pod 'GoogleUtilities', '= 5.3.6'

  target 'HubzuApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HubzuAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
